[package]
name = "dsync"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47.1", features = ["full"] }
blake3 = { version = "1.8.2", features = ["pure"] }
bincode = "1.3.3"
notify = "8.2.0"
serde = { version = "1.0.219", features = ["derive"] }
anyhow = "1.0.99"
clap = { version = "4.5.48", features = ["derive"] }
pathdiff = "0.2.3"
mdns-sd = "0.11"
hostname = "0.4"
get_if_addrs = "0.5"
ed25519-dalek = { version = "2", features = ["rand_core"] }
rand = "0.8"
hex = "0.4"
walkdir = "2.5.0"
indicatif = "0.18.3"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "chrono"] }
lz4_flex = "0.12.0"
toml = "1.0.4"
dirs = "6.0.0"
globset = "0.4.18"
governor = "0.10.4"
nonzero_ext = "0.3.0"
x25519-dalek = { version = "2.0.1", features = ["static_secrets"] }
chacha20poly1305 = "0.10.1"
